# file: sonar-project.properties
sonar.host.url=http://localhost:9000

sonar.projectKey=scholarPro
sonar.projectName=ScholarPro Backend
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.spec.ts
sonar.exclusions=tests/**/*,**/node_modules/**/*,dist/**/*
sonar.javascript.lcov.reportPaths=coverage/lcov.info