export const dashboardStats = {
  newApplications: 168,
  totalApplicants: 1125,
  gender: { female: 599, male: 526, total: 1125 },
  majors: [
    { major: "Business Intelligence", count: 320 },
    { major: "Software ", count: 280 },
    { major: "Data Science & AI", count: 240 },
    { major: "Cybersecurity", count: 170 },
    { major: "Cloud ", count: 95 },
    { major: "Network Engineering", count: 20 },
    { major: "Other", count: 0 },
  ],
};

export const dashboardProvinceData = [
  { province: "Phnom Penh" },
  { province: "Siem Reap" },
  { province: "Battambang" },
  { province: "Kampot" },
  { province: "Kandal" },
  { province: "Takeo" },
  { province: "Prey Veng" },
  { province: "Svay Rieng" },
  { province: "Banteay Meanchey" },
  { province: "Pursat" },
  { province: "Kep" },
  { province: "Koh Kong" },
  { province: "Mondulkiri" },
  { province: "Ratanakiri" },
  { province: "Stung Treng" },
  { province: "Preah Vihear" },
  { province: "Tboung Khmum" },
  { province: "Sihanoukville" },
  { province: "Kampong Cham" },
  { province: "Kratie" },
  { province: "Oddar Meanchey" },
  { province: "Kampong Speu" },
  { province: "Kampong Thom" },
  { province: "Battambang" },
  { province: "Chamkar Mon" },
];
